development:
  adapter: postgresql
  encoding: unicode
  database: calendar_development
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: calendar_test
  pool: 5
  host: localhost
  password:

production:
  adapter: postgresql
  database: calendar/production
  pool: 5
