development:
  adapter: postgresql
  database: calendar_development
  host: localhost
  username: rrgayhart
  password:

test:
  adapter: postgresql
  database: calendar_test
  host: localhost
  username: rrgayhart
  password:
